#!/bin/bash

## To use this script run:
#        apt-get update  && apt-get install curl && curl https://raw.githubusercontent.com/KyleHillUK/Debian/main/autoupgrade | bash

apt-get update
yes | apt-get dist-upgrade
yes Y| apt-get install unattended-upgrades apt-listchanges
sleep 1
